/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Asanka
 */
public class Kitchen_Manager extends javax.swing.JFrame {
String RealName;
    /**
     * Creates new form Kitchen_Manager
     */
    
    int Emp_ID;
    public Kitchen_Manager(int EmpID,String realName) {
        initComponents();
      //  jLabel4.setText(""+EmpID);
        Show_jTable() ;
      Show_jTable1();
       Emp_ID=EmpID;
       setLocationRelativeTo(null);
       RealName=realName;
       jLabel_Realname.setText(realName);
       setIcon();
    }

    
       private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png")));
        }

    
    Kitchen_Manager() {
        throw new UnsupportedOperationException("Not supported yet.");
      
        
   
//To change body of generated methods, choose Tools | Templates.
    }

    
    //table view
    public ArrayList<Selling_Details> getuserList() {

        ArrayList<Selling_Details> userList = new ArrayList<Selling_Details>();
        Connection connection = DBconnect.connectdb();

        String query = " select Table_No,Emp_Id,Product_Name,Size,Qty from Orders where Status = 0   ";
        Statement st;
        ResultSet rs;

        try {
            st = connection.createStatement();
            rs = st.executeQuery(query);
            Selling_Details user;
            while (rs.next()) {
                user = new Selling_Details(rs.getInt("Table_No"),rs.getInt("Emp_Id"),rs.getString("Product_Name"), rs.getString("Size"), rs.getFloat("Qty"));
                userList.add(user);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return userList;
    }

    //Display data
    public void Show_jTable() {

        ArrayList<Selling_Details> list = getuserList();
        DefaultTableModel model = (DefaultTableModel) jTable_In.getModel();

        Object[] row = new Object[5];
        for (int i = 0; i < list.size(); i++) {
            row[0] = list.get(i).getTable_no();
            row[1] = list.get(i).getEmp_id();
            row[2] = list.get(i).getItem();
            row[3] = list.get(i).getSize();
            row[4] = list.get(i).getQty();

            model.addRow(row);

        }

    }

   
    //for Out table
    public ArrayList<Selling_Details> getuserList1() {

        ArrayList<Selling_Details> userList = new ArrayList<Selling_Details>();
        Connection connection = DBconnect.connectdb();

        String query = " select Table_No,Emp_Id,Product_Name,Size,Qty from Orders where Status = 1   ";
        Statement st;
        ResultSet rs;

        try {
            st = connection.createStatement();
            rs = st.executeQuery(query);
            Selling_Details user;
            while (rs.next()) {
                user = new Selling_Details(rs.getInt("Table_No"),rs.getInt("Emp_Id"),rs.getString("Product_Name"), rs.getString("Size"), rs.getFloat("Qty"));
                userList.add(user);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return userList;
    }

    //Display data
    public void Show_jTable1() {

        ArrayList<Selling_Details> list = getuserList1();
        DefaultTableModel model = (DefaultTableModel) jTable_out.getModel();

        Object[] row = new Object[5];
        for (int i = 0; i < list.size(); i++) {
            row[0] = list.get(i).getTable_no();
            row[1] = list.get(i).getEmp_id();
            row[2] = list.get(i).getItem();
            row[3] = list.get(i).getSize();
            row[4] = list.get(i).getQty();

            model.addRow(row);

        }

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_In = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_out = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jTextField_table_no = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField_product_name = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField_qty = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel_Realname = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kitchen Manager");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Order Processing");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 190, -1, -1));

        jTable_In.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable_In.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Table No", "Employee ID", "Product Name", "Size", "Quantity"
            }
        ));
        jTable_In.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_InMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_In);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, 240));

        jTable_out.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable_out.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Table No", "Employee ID", "Product Name", "Size", "Quantity"
            }
        ));
        jTable_out.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_outMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable_out);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 300, -1, 240));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel2.setText("In");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel3.setText("Out");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 260, -1, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/approved.png"))); // NOI18N
        jButton1.setText("Finish");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 550, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Table No");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 330, -1, -1));

        jTextField_table_no.setEnabled(false);
        getContentPane().add(jTextField_table_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 360, 114, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Product Name");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 400, -1, -1));

        jTextField_product_name.setEnabled(false);
        getContentPane().add(jTextField_product_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 430, 114, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Quantity");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 470, -1, -1));

        jTextField_qty.setEnabled(false);
        getContentPane().add(jTextField_qty, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 500, 114, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/cancel.png"))); // NOI18N
        jButton2.setText("Cancel");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 550, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 0, 0));
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/logO.png"))); // NOI18N
        jLabel15.setText("LogOut");
        jLabel15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 10, -1, -1));

        jLabel_Realname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_Realname.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Realname.setText("name");
        getContentPane().add(jLabel_Realname, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 10, 140, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/inventory_keeper_1.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable_InMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_InMouseClicked
        int i = jTable_In.getSelectedRow();
        TableModel model = jTable_In.getModel();
        jTextField_product_name.setText(model.getValueAt(i, 2).toString());
        jTextField_table_no.setText(model.getValueAt(i, 0).toString());
        jTextField_qty.setText(model.getValueAt(i, 4).toString());
    }//GEN-LAST:event_jTable_InMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       if(!(jTextField_table_no.getText().equals(""))){
       int reply= JOptionPane.showConfirmDialog(null, "Are you Sure", "Save Order", JOptionPane.YES_NO_OPTION);
       
         if (reply == JOptionPane.YES_OPTION) {
          String query = "UPDATE Orders SET Status=1 WHERE Table_No='" + jTextField_table_no.getText() + "' and Product_Name='" + jTextField_product_name.getText() + "' and Qty='" + jTextField_qty.getText() + "' ";
        
        executeQuery(query);
       
       }
        
        }
       else{
          JOptionPane.showMessageDialog(rootPane, " Sorry! Please Select Order first...", "Warning", JOptionPane.WARNING_MESSAGE);

         
         }
        
       
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable_outMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_outMouseClicked
       int i = jTable_out.getSelectedRow();
        TableModel model = jTable_out.getModel();
        jTextField_product_name.setText(model.getValueAt(i, 2).toString());
        jTextField_table_no.setText(model.getValueAt(i, 0).toString());
        jTextField_qty.setText(model.getValueAt(i, 4).toString());
    }//GEN-LAST:event_jTable_outMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

         if(!(jTextField_table_no.getText().equals(""))){
        
        int reply= JOptionPane.showConfirmDialog(null, "Are you Sure", "Save Order", JOptionPane.YES_NO_OPTION);
       
         if (reply == JOptionPane.YES_OPTION) {
          String query = "UPDATE Orders SET Status=0 WHERE Table_No='" + jTextField_table_no.getText() + "' and Product_Name='" + jTextField_product_name.getText() + "' and Qty='" + jTextField_qty.getText() + "' ";
        
        executeQuery(query);
        }
          }
       else{
          JOptionPane.showMessageDialog(rootPane, " Sorry! Please Select Order first...", "Warning", JOptionPane.WARNING_MESSAGE);

         
         }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        int reply = JOptionPane.showConfirmDialog(null, "Are you Sure", "Loging Out", JOptionPane.YES_NO_OPTION);

        if (reply == JOptionPane.YES_OPTION) {
            new Login().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jLabel15MouseClicked

    
     public void executeQuery(String query) {

        Connection con = DBconnect.connectdb();
        Statement st;

        try {
            st = con.createStatement();
            st.executeUpdate(query);

            DefaultTableModel model = (DefaultTableModel) jTable_out.getModel();
            model.setRowCount(0);
           
          Show_jTable1();
           Show_jTable();
           this.dispose();
           new Kitchen_Manager(Emp_ID,RealName).setVisible(true);

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);

        }

    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kitchen_Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kitchen_Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kitchen_Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kitchen_Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kitchen_Manager().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel_Realname;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable_In;
    private javax.swing.JTable jTable_out;
    private javax.swing.JTextField jTextField_product_name;
    private javax.swing.JTextField jTextField_qty;
    private javax.swing.JTextField jTextField_table_no;
    // End of variables declaration//GEN-END:variables
}
