/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import com.sun.glass.events.KeyEvent;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Asanka
 */
public class Oder extends javax.swing.JFrame {

    String RealName;
    /**
     * Creates new form Oder
     */

    int Emp_Id;

    public Oder(int EmpID, String realName) {
        initComponents();
        setLocationRelativeTo(null);
        // jLabel_Emp_Id.setText("" + EmpID);
        Show_jTable1();
        Emp_Id = EmpID;
        RealName = realName;
        jLabel_Realname.setText(realName);
        Bindcombo();
        setIcon();
    }

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png")));
    }

    Oder() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jTable_Complete = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jTextField_Product_Code = new javax.swing.JTextField();
        jTextField_Qty = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField_Table_No = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jTextField_Product = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel_price = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField_table_no_com = new javax.swing.JTextField();
        jTextField_emp_id_com = new javax.swing.JTextField();
        jTextField_productName_com = new javax.swing.JTextField();
        jTextField4_qty_com = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel_Realname = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Order Form");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable_Complete.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable_Complete.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Table No", "Employee Name", "Product Name", "Quantity", "Size", "Status"
            }
        ));
        jTable_Complete.setOpaque(false);
        jTable_Complete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_CompleteMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable_Complete);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 440, 652, 240));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setOpaque(false);

        jTextField_Product_Code.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Product_CodeActionPerformed(evt);
            }
        });
        jTextField_Product_Code.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_Product_CodeKeyTyped(evt);
            }
        });

        jTextField_Qty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_QtyActionPerformed(evt);
            }
        });
        jTextField_Qty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_QtyKeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Size");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Qty");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Product Code");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Table No");

        jTextField_Table_No.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Table_NoActionPerformed(evt);
            }
        });
        jTextField_Table_No.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_Table_NoKeyTyped(evt);
            }
        });

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Name", "Size", "Quantity"
            }
        ));
        jTable1.setOpaque(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Order Form");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/approved.png"))); // NOI18N
        jButton1.setText("Finish");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "M", "L", "S" }));
        jComboBox1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Product");

        jTextField_Product.setEnabled(false);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/cancel.png"))); // NOI18N
        jButton2.setText("Delete");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("Price");

        jLabel_price.setText("0");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Product" }));
        jComboBox2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox2MouseClicked(evt);
            }
        });
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel4))
                                    .addGap(20, 20, 20)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextField_Table_No, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                                        .addComponent(jTextField_Product_Code))
                                    .addGap(34, 34, 34)
                                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addComponent(jTextField_Product, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(39, 39, 39)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(46, 46, 46)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel_price)
                                            .addComponent(jLabel17))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextField_Qty, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5))
                                        .addGap(59, 59, 59)
                                        .addComponent(jButton2))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField_Table_No, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField_Product_Code, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel17)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel_price))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(jLabel9))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField_Product, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextField_Qty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(18, 18, 18))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel7.setText("Completed Orders");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 400, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel8.setText("Waiter Main Page");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 250, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setOpaque(false);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Table No");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Employee Name");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Product name");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Quantity");

        jTextField_table_no_com.setEnabled(false);

        jTextField_emp_id_com.setEnabled(false);

        jTextField_productName_com.setEnabled(false);

        jTextField4_qty_com.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_table_no_com, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jTextField_emp_id_com, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_productName_com, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(52, 52, 52)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jTextField4_qty_com, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_table_no_com, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_emp_id_com, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_productName_com, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4_qty_com, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 690, -1, -1));

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/approved.png"))); // NOI18N
        jButton3.setText("Served");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 810, 237, 32));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 0, 0));
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/logO.png"))); // NOI18N
        jLabel15.setText("LogOut");
        jLabel15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 10, -1, -1));

        jLabel_Realname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_Realname.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Realname.setText("name");
        getContentPane().add(jLabel_Realname, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 10, 140, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/oder.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1230, 930));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_Product_CodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Product_CodeActionPerformed
        productSelect();
    }//GEN-LAST:event_jTextField_Product_CodeActionPerformed

    //fill item name combo
    public void Bindcombo() {

        MyQuery5 mq = new MyQuery5();
        HashMap<String, Integer> map = mq.populateCombo();
        for (String s : map.keySet()) {

            jComboBox2.addItem(s);

        }

    }

    public void productSelect() {
        String sql = "SELECT Product_Name,Qty,Selling_Price FROM Product where Product_Code='" + jTextField_Product_Code.getText() + "' ";

        try {

            PreparedStatement pst = DBconnect.connectdb().prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {

                jTextField_Product.setText(rs.getString(1));
                jLabel_price.setText("" + rs.getFloat(3));
                jTextField_Qty.requestFocus();

            }
            pst.close();
            rs.close();
        } catch (SQLException e) {
            System.out.println(e);
        }
    }

    private void jTextField_QtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_QtyActionPerformed
if(!(jTextField_Product_Code.getText().equals("")) && (!(jTextField_Table_No.getText().equals(""))) && (!(jTextField_Qty.getText().equals("")))){

    
    try {
           
                 Connection connection = DBconnect.connectdb();
                Statement st;
            ResultSet rs1;
            st = connection.createStatement();
            rs1=st.executeQuery("select Qty from Product where Product_Code='"+jTextField_Product_Code.getText()+"' ");
                
            if(rs1.next()){
            
                float CurrentQty=rs1.getFloat(1);
                
                if(CurrentQty>=Float.parseFloat(jTextField_Qty.getText())){
                
                 
      String query = " insert into Orders (Table_No,Product_Name,Qty,Emp_Id,Size,Status,Price,Total_Amount) values('" + jTextField_Table_No.getText() + "','" + jTextField_Product.getText() + "','" + jTextField_Qty.getText() + "','" + Emp_Id + "','" + jComboBox1.getSelectedItem() + "',0,'" + jLabel_price.getText() + "',0)";
        executeQuery(query);
        clear();
                
                }else{
                
                 JOptionPane.showMessageDialog(rootPane, " Sorry! That Number of Quantity Not Have", "Warning", JOptionPane.WARNING_MESSAGE);

                
                }
                
            
            
            }
            } catch (Exception e) {
            }
    
    

}else{

 JOptionPane.showMessageDialog(rootPane, " Sorry! Please input Product code or Table No", "Warning", JOptionPane.WARNING_MESSAGE);


}
        

    }//GEN-LAST:event_jTextField_QtyActionPerformed

    public void clear(){
    jTextField_Product_Code.setText("");
    jTextField_Product.setText("");
     jTextField_Qty.setText("");
     jLabel_price.setText("0");
     jComboBox1.setSelectedIndex(0);
     jTextField_Product_Code.requestFocus();
     
    
    
    
    }
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int i = jTable1.getSelectedRow();
        TableModel model = jTable1.getModel();
        jTextField_Product.setText(model.getValueAt(i, 0).toString());
        jTextField_Qty.setText(model.getValueAt(i, 2).toString());

    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(!(jTextField_Qty.getText().equals(""))){
        
            
            
         String query = "DELETE FROM Orders WHERE Product_Name='" + jTextField_Product.getText() + "' and Qty= '" + jTextField_Qty.getText() + "'";
        executeQuery(query);
        
        
        }else{
        
          JOptionPane.showMessageDialog(rootPane, " Sorry! Please Select Order first...", "Warning", JOptionPane.WARNING_MESSAGE);

        }
        
        
        

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
if(!(jTextField_Table_No.getText().equals(""))){
int reply = JOptionPane.showConfirmDialog(null, "Are you Sure", "Save Order", JOptionPane.YES_NO_OPTION);

        if (reply == JOptionPane.YES_OPTION) {
            this.dispose();
            new Oder(Emp_Id, RealName).setVisible(true);
        }


}else{


}
        

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable_CompleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_CompleteMouseClicked
        int i = jTable_Complete.getSelectedRow();
        TableModel model = jTable_Complete.getModel();
        jTextField_table_no_com.setText(model.getValueAt(i, 0).toString());
        jTextField_emp_id_com.setText(model.getValueAt(i, 1).toString());
        jTextField_productName_com.setText(model.getValueAt(i, 2).toString());
        jTextField4_qty_com.setText(model.getValueAt(i, 3).toString());
    }//GEN-LAST:event_jTable_CompleteMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       if(!(jTextField_productName_com.getText().equals(""))){
        
        int reply = JOptionPane.showConfirmDialog(null, "Are you Sure", "Serve Order", JOptionPane.YES_NO_OPTION);

        if (reply == JOptionPane.YES_OPTION) {
           Connection connection = DBconnect.connectdb();
            try {
                
            int Emp_id=0;
            String query3 = " select Emp_Id from Employee  where  Employee_name='"+jTextField_emp_id_com.getText()+"'  ";
            Statement st;
            ResultSet rsss;
            st = connection.createStatement();
            rsss = st.executeQuery(query3);
            
            if(rsss.next()){
            
            Emp_id=rsss.getInt(1);
            String query11 = "UPDATE Orders SET Status=2 WHERE Table_No='"+jTextField_table_no_com.getText()+"' and Product_Name='"+jTextField_productName_com.getText()+"' and Qty='"+jTextField4_qty_com.getText()+"' and Emp_Id='"+Emp_id+"' ";

            executeQuery1(query11);
            }
            
             
            }catch(Exception e){
            
            }
           
        }
       
       
       }else{
       
        JOptionPane.showMessageDialog(rootPane, " Sorry! Please Select Order first...", "Warning", JOptionPane.WARNING_MESSAGE);

       }
        
       

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField_Table_NoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Table_NoActionPerformed
        // TODO add your handling code here:
        jTextField_Product_Code.requestFocus();
    }//GEN-LAST:event_jTextField_Table_NoActionPerformed

    private void jComboBox2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox2MouseClicked

    }//GEN-LAST:event_jComboBox2MouseClicked

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        MyQuery5 mq = new MyQuery5();
        HashMap<String, Integer> map = mq.populateCombo();

        jTextField_Product_Code.setText(map.get(jComboBox2.getSelectedItem().toString()).toString());

        productSelect();
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jTextField_Table_NoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_Table_NoKeyTyped
      char c = evt.getKeyChar();//numbers only
        if (!(Character.isDigit(c) || (c == KeyEvent.VK_ENTER) || (c == KeyEvent.VK_BACKSPACE) || (c == KeyEvent.VK_DELETE))) {
            getToolkit().beep();
            evt.consume();
        }  
    }//GEN-LAST:event_jTextField_Table_NoKeyTyped

    private void jTextField_Product_CodeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_Product_CodeKeyTyped
      char c = evt.getKeyChar();//Only numbers can enter (4)
        if ((jTextField_Product_Code.getText().length() >= 4) || (c == KeyEvent.VK_SPACE) || (Character.isLetter(c)))//   cannot input this items
        {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_jTextField_Product_CodeKeyTyped

    private void jTextField_QtyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_QtyKeyTyped
         char c = evt.getKeyChar();//Rupee and decimal  only
        if (!(Character.isDigit(c) || (c == KeyEvent.VK_ENTER) || (c == KeyEvent.VK_PERIOD) || (c == KeyEvent.VK_BACKSPACE) || (c == KeyEvent.VK_DELETE))) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_jTextField_QtyKeyTyped

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        int reply = JOptionPane.showConfirmDialog(null, "Are you Sure", "Loging Out", JOptionPane.YES_NO_OPTION);

        if (reply == JOptionPane.YES_OPTION) {
            new Login().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jLabel15MouseClicked

    //table view
    public ArrayList<Selling_Details> getuserList() {

        ArrayList<Selling_Details> userList = new ArrayList<Selling_Details>();
        Connection connection = DBconnect.connectdb();

        String query = " select Product_Name,Size,Qty from Orders  where Table_No='" + jTextField_Table_No.getText() + "' ";
        Statement st;
        ResultSet rs;

        try {
            st = connection.createStatement();
            rs = st.executeQuery(query);
            Selling_Details user;
            while (rs.next()) {
                user = new Selling_Details(rs.getString("Product_Name"), rs.getString("Size"), rs.getFloat("Qty"));
                userList.add(user);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return userList;
    }

    //Display data
    public void Show_jTable() {

        ArrayList<Selling_Details> list = getuserList();
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

        Object[] row = new Object[3];
        for (int i = 0; i < list.size(); i++) {
            row[0] = list.get(i).getItem();
            row[1] = list.get(i).getSize();
            row[2] = list.get(i).getQty();

            model.addRow(row);

        }

    }

    public void executeQuery(String query) {

        Connection con = DBconnect.connectdb();
        Statement st;

        try {
            st = con.createStatement();
            st.executeUpdate(query);

            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setRowCount(0);
            Show_jTable();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);

        }

    }

    public void executeQuery1(String query) {

        Connection con = DBconnect.connectdb();
        Statement st;

        try {
            st = con.createStatement();
            st.executeUpdate(query);

            this.dispose();
            new Oder(Emp_Id, RealName).setVisible(true);

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);

        }

    }

    //table view for completed table
    public ArrayList<Selling_Details> getuserList1() {

        ArrayList<Selling_Details> userList = new ArrayList<Selling_Details>();
        Connection connection = DBconnect.connectdb();

        String query = " select * from Orders  where  Status=1 or Status=2  ";
        Statement st;
        ResultSet rs;

        try {
            st = connection.createStatement();
            rs = st.executeQuery(query);
            Selling_Details user;
            while (rs.next()) {
                user = new Selling_Details(rs.getInt("Table_No"), rs.getInt("Emp_Id"), rs.getString("Product_Name"), rs.getString("Size"), rs.getFloat("Qty"), rs.getInt("Status"));
                userList.add(user);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return userList;
    }

    //Display data
    public void Show_jTable1() {

        ArrayList<Selling_Details> list = getuserList1();
        DefaultTableModel model = (DefaultTableModel) jTable_Complete.getModel();

        Object[] row = new Object[6];

        for (int i = 0; i < list.size(); i++) {
String Emp_name=null;
            int empId = list.get(i).getEmp_id();
            Connection connection = DBconnect.connectdb();
            try {
                
            
            String query3 = " select Employee_Name from Employee  where  Emp_Id='" + empId + "'  ";
            Statement st;
            ResultSet rss;
            st = connection.createStatement();
            rss = st.executeQuery(query3);
            
            if(rss.next()){
Emp_name=rss.getString(1);
            row[0] = list.get(i).getTable_no();
            row[1] = Emp_name;
            row[2] = list.get(i).getItem();
            row[3] = list.get(i).getQty();
            row[4] = list.get(i).getSize();
            row[5] = list.get(i).getStatus();

            model.addRow(row);

            } }
             catch (Exception e) {
            }

    }}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Oder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Oder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Oder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Oder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Oder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_Realname;
    private javax.swing.JLabel jLabel_price;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable_Complete;
    private javax.swing.JTextField jTextField4_qty_com;
    private javax.swing.JTextField jTextField_Product;
    private javax.swing.JTextField jTextField_Product_Code;
    private javax.swing.JTextField jTextField_Qty;
    private javax.swing.JTextField jTextField_Table_No;
    private javax.swing.JTextField jTextField_emp_id_com;
    private javax.swing.JTextField jTextField_productName_com;
    private javax.swing.JTextField jTextField_table_no_com;
    // End of variables declaration//GEN-END:variables
}
